config/routes.rb
Rails.application.routes.draw do
  post 'github_events/payload', constraints: { format: 'json' }

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :user_settings, only: [:edit, :update]
  resource :notifications, only: [:index]

  root to: "notifications#index"
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :pull_request
  validates :pull_request, presence: true

  has_and_belongs_to_many :notified_users, join_table: :notified_users, class_name: 'User'
end

app/models/pull_request.rb
class PullRequest < ActiveRecord::Base
  belongs_to :repository

  validates :number, presence: true
  validates :repository, presence: true
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  belongs_to :access_via, class_name: 'User'

  validates :name, presence: true
  validates :webhook_secret, presence: true
  validates :access_via, presence: true

  def access_token
    access_via.token
  end

  def compute_webhook_signature(data)
    'sha1=' + OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha1'), webhook_secret, data)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:github]

  has_and_belongs_to_many :notifications, join_table: :notified_users

  validates :github_username, presence: true, uniqueness: true
  validates :uid, presence: true

  attr_encrypted :token, key: ->(_) { UserTokenKey.get }
  attr_encrypted :token_old, key: 'hello', algorithm: 'aes-256-cbc', mode: :single_iv_and_salt, insecure_mode: true

  def self.from_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.github_username = auth.info.nickname
      user.email = auth.info.email
      user.token = auth.credentials.token
      user.password = Devise.friendly_token[0,20]
    end

    token = auth.credentials.token

    if token != user.token
      user.update_attributes!(token: token)
    end

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/github_events_controller.rb
require 'ladle/notify_stewards_of_pull_request_changes'

class GithubEventsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :find_repository, only: [:payload]
  before_action :verify_signature, only: [:payload]

  def payload
    number              = params.require(:number)
    pull_request_params = params.require(:pull_request)
    pull_request_state  = pull_request_params.require(:state)

    Rails.logger.info "New pull ##{number} for #{@repository.name}. Running handler..."

    if pull_request_state == 'open'
      pull_request = find_pull_request(number:   number,
                                       html_url: pull_request_params[:html_url].presence,
                                       title:    pull_request_params[:title],
                                       body:     pull_request_params[:body])

      Ladle::NotifyStewardsOfPullRequestChanges.(pull_request)
    else
      Rails.logger.info 'Pull closed, doing nothing.'
    end

    head :ok
  end

  private

  def find_pull_request(number:, html_url:, title:, body:)
    ActiveRecord::Base.transaction do
      pull_request = PullRequest.find_or_create_by!(repository: @repository, number: number, html_url: html_url)
      pull_request.update_attributes!(
        title: title,
        body:  body
      )
      pull_request
    end
  end

  def find_repository
    repository = params.require(:repository)

    @repository = Repository.find_by_name(repository[:full_name])
    unless @repository
      head :forbidden
    end
  end

  def verify_signature
    request.body.rewind
    payload_body = request.body.read

    signature = @repository.compute_webhook_signature(payload_body)

    unless Rack::Utils.secure_compare(signature, request.env['HTTP_X_HUB_SIGNATURE'] || '')
      Rails.logger.info "Signature mismatch - recv: <#{request.env['HTTP_X_HUB_SIGNATURE'].inspect}> calc <#{signature.inspect}>"
      head :forbidden
    end
  end
end

app/controllers/notifications_controller.rb
require 'delegate'

class NotificationsController < AuthenticatedController

  class NotificationPresenter < SimpleDelegator
    def link
      pull_request.html_url
    end

    def title
      "[#{pull_request.repository.name}] #{pull_request.title}"
    end
  end

  def index
    @notifications = current_user.notifications.order('created_at DESC').map do |notification|
      NotificationPresenter.new(notification)
    end
  end
end

app/controllers/user_settings_controller.rb
class UserSettingsController < AuthenticatedController
  class UserSettingsView
    attr_reader :user, :emails

    def initialize(user, emails)
      @user   = user
      @emails = emails
    end
  end

  def edit
    create_edit_view(current_user)
  end

  def update
    user_params = params.require(:user).permit(:email)
    email = user_params[:email]

    user = current_user
    user.email = email
    user.save!

    flash.notice = "Settings successfully updated."
    redirect_to edit_user_settings_path
  rescue ActiveRecord::RecordInvalid => e
    flash.now.alert = "Failed updating settings."
    create_edit_view(e.record)
    render :edit, status: :unprocessable_entity
  end

  private

  def create_edit_view(user)
    @view = UserSettingsView.new(user, notification_emails(user))
  end

  def notification_emails(user)
    client = Octokit::Client.new(access_token: user.token)

    verified_emails = client.emails.select(&:verified)

    emails = verified_emails.map(&:email)

    emails.reject do |email|
      email =~ /github\.com$/
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if user_is_permitted_to_login?(@user)
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      set_flash_message(:alert, :failure, kind: "Github", reason: "your account does not have access") if is_navigational_format?
      redirect_to new_user_session_path
    end
  end

  private

  def user_is_permitted_to_login?(user)
    if ! user.persisted?
      return false
    end

    github_client = Octokit::Client.new(access_token: user.token)
    organizations = github_client.orgs.map { |org| org[:login] }

    Rails.application.github_config.organization_permitted?(organizations)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_events_helper.rb
module GithubEventsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ladle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "LADLE", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="nav-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to('Notifications', root_path) %></li>
            <li><%= link_to('Settings', edit_user_settings_path ) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <% if notice %>
    <div class="alert alert-success" role="alert"><%= notice %></div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger" role="alert"><%= alert %></div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/notifications/_notification.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>
      <%= notification.title %>
      <div class="pull-right">
        <%= time_tag notification.created_at, title: notification.created_at do %>
          <%= time_ago_in_words(notification.created_at) %> ago
        <% end %>
      </div>
    </h4>
  </div>
  <div class="panel-body">
    <%= link_to notification.link, notification.link, target: '_blank' %>
  </div>
</div>

app/views/notifications/index.html.erb
<h1>Notifications</h1>
<%= render partial: "notification", collection: @notifications %>

app/views/user_settings/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Settings</h4>
  </div>
  <div class="panel-body">
    <%= simple_form_for(@view.user, url: user_settings_path, method: :patch) do |f| %>
      <%= f.input :email, collection: @view.emails, include_blank: false, label: 'Notification Email' %>
      <%= f.button :submit, value: "Update settings", class: 'btn-success' %>
    <% end %>
  </div>
</div>

app/views/user_settings/update.html.erb
<h1>UserSettings#update</h1>
<p>Find me in app/views/user_settings/update.html.erb</p>